#!/bin/sh
#
# Copyright (c) 2011
# Antti Harri <iku@openbsd.fi>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

BASE=$(cd -- "$(dirname -- "$0")"; pwd)
INST_PREFIX=/usr/local

if [ -f "${BASE}/attach.conf" ] && [ -f "${INST_PREFIX}/share/ohtools/hotplug/attach.sh" ]; then
	. "${BASE}/attach.conf"
	if [ -n "$DEBUG" ]; then
		mkdir -p /root/hotplug-debug || exit 1
		exec > "/root/hotplug-debug/$2.txt" 2>&1
		set -x
	fi
	. "${INST_PREFIX}/share/ohtools/hotplug/attach.sh" "$@"
fi
