#!/bin/sh
#
# $Id: attach,v 1.9 2007/11/10 23:22:58 iku Exp $
#

BASE=$(cd -- "$(dirname -- "$0")"; pwd)
INST_PREFIX=/usr/local

if [ -f "${BASE}/attach.conf" ] && [ -f "${INST_PREFIX}/share/ohtools/hotplug/attach.sh" ]; then
	. "${BASE}/attach.conf"
	. "${INST_PREFIX}/share/ohtools/hotplug/attach.sh"
fi
