#!/bin/sh
#
# $Id: attach,v 1.8 2007/11/09 19:48:20 iku Exp $
#

BASE=$(cd -- "$(dirname -- "$0")"; pwd)
OHTOOLS_INST_PREFIX=/usr/local

if [ -f "${BASE}/attach.conf" ] && [ -f "${OHTOOLS_INST_PREFIX}/libexec/hotplug_attach.sh" ]; then
	. "${BASE}/attach.conf"
	. "${OHTOOLS_INST_PREFIX}/libexec/hotplug_attach.sh"
fi
