#!/bin/sh

VERBOSE=1
BASE=$(cd -- "$(dirname -- "$0")"; pwd)
CONFIG="${BASE}/.config"

# pick up functions
. "$BASE/functions.sh"

# check for first run
get_config state
if [ "$?" -ne "0" ]; then
	set_config state install_kernel
fi

get_config state
case "$_VAL" in
	"install_kernel" ) # in the middle of fetching files

		# SOURCE
		get_config source
		if [ "$?" -ne "0" ]; then
			init_source
		else
			source=$_VAL
		fi

		# FILE FETCHING
		# always needed files
		echo "Fetch source $source."
		echo "Fetching MD5 sums and index."
		fetch_files MD5 index.txt

		echo "Fetching new kernels."
		fetch_files --verify bsd.rd bsd bsd.mp

		# fetch only selected files
		echo "Fetching base packages."
		PKGS="base etc comp game man misc xbase xetc xfont xserv xshare"

		for pkg in $PKGS; do
			get_config $pkg
			if [ "$?" -ne "0" ]; then
				echo -n "Install $pkg ? (y/N) "
				read ans
				set_config $pkg "$ans"
				if [ "$?" -ne "0" ]; then
					echo "Failed to set configuration."
					exit 1
				fi
			else
				ans=$_VAL
			fi

			# Fetch it
			if [ "$ans" = "y" ]; then
				query_index $pkg
				fetch_files --verify $_VAL
			fi
		done

		# now install kernels
		echo "About to install kernels, are you sure? (y/N) "
		read ans
		if [ "$ans" != "y" ]; then
			echo "ABORTED!"
			exit 1
		fi

		cp -f /bsd /bsd.orig
		cp -f $BASE/tmp/bsd* /

		echo "Kernel(s) installed"

		echo "New config state written, reboot and re-run this script after reboot"
		set_config state install_base
	;;
	"install_base" )
		# install the base packages
		echo "About to install base packages, are you sure? (y/N) "
		read ans
		if [ "$ans" != "y" ]; then
			echo "ABORTED!"
			exit 1
		fi

		for pkg in $BASE/tmp/*.tgz; do
			echo "Installing $pkg"
			(cd / && tar zxfp "$pkg") || break
		done

		echo "Base installed"

		set_config state install_kernel
	;;
esac
