#!/bin/sh
#
# Original file:
# Copyright (c) 2006 Andreas Delfino <adelfino@gmail.com>
#
# Tweaks:
# Copyright (c) 2009 Antti Harri <iku@openbsd.fi>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

function move_cursor_up {
	tput up dl 0
}

function check_for_packages {
	local purge
	for package in $(pkg_info -t | cut -f 1 -d ' '); do
		echo "Checking for $package"
		if ! { package_name=$( echo "$package" | sed "s/-[^-]\{1,\}$//" ); grep -qs \
"$package_name" "$HOME/.pkg_check.conf"; } then
			move_cursor_up
			echo -n "No package depends on $package, would you like to delete it? y/n "
			while true; do
				read answer
				case $answer in
					y)
						purge="$purge $package"
						let "deleted_packages = 1"
						break
						;;
					n )
						echo "$package_name" >> "$HOME/.pkg_check.conf"
						break
						;;
					* )
						echo -n 'y/n '
						;;
				esac
			done
		else
			move_cursor_up
		fi
	done
	if [ -n "$purge" ]; then
		pkg_delete $purge
	fi
}

# Check for root privileges.
if [ "$(whoami)" != "root" ]; then
	echo "You need to be root to run this."
	exit 1
fi

while true; do
	check_for_packages
	if ! let "deleted_packages"; then
		break
	fi
	let "deleted_packages = 0"

	echo -n "\nRunning from the top to see new obsolete packages."
done
