#!/bin/sh

#
# $Id: pkgpurge,v 1.2 2009/09/23 19:06:30 iku Exp $
#

function move_cursor_up {
	tput up dl 0
}

function check_for_packages {
	local purge
	for package in $(pkg_info -t | cut -f 1 -d ' '); do
		echo "Checking for $package"
		if ! { package_name=$( echo "$package" | sed "s/-[^-]\{1,\}$//" ); grep -qs \
"$package_name" "$HOME/.pkg_check.conf"; } then
			move_cursor_up
			echo -n "No package depends on $package, would you like to delete it? y/n "
			while true; do
				read answer
				case $answer in
					y)
						purge="$purge $package"
						let "deleted_packages = 1"
						break
						;;
					n )
						echo "$package_name" >> "$HOME/.pkg_check.conf"
						break
						;;
					* )
						echo -n 'y/n '
						;;
				esac
			done
		else
			move_cursor_up
		fi
	done
	if [ -n "$purge" ]; then
		sudo pkg_delete $purge
	fi
}

while true; do
	check_for_packages
	if ! let "deleted_packages"; then
		break
	fi
	let "deleted_packages = 0"

	echo -n "\nRunning from the top to see new obsolete packages."
done
