#!/bin/sh
#
# $Id: tempy,v 1.3 2007/11/09 20:19:17 iku Exp $
#
# Copyright (c) 2007 Antti Harri <iku@openbsd.fi>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

# Configuration
MASTER=master.html
TPLS=" \
	index \
	news \
	stuff \
	supported \
	games \
	docs \
	fordevs \
	contact"
PERMS=0600
GALLERY_FILE=screens
GALLERY_HTML=screens.html
GALLERY_DESC=descriptions
GALLERY_ORIG=screenshots
GALLERY_THUMB=thumbnails
GALLERY_DIMS=200x200

# Target aliases
default="templates"

# Check for configuration in current working directory,
# it will override settings defined in the file header
# section.

if [ -f ".tempy" ]; then
	. ./.tempy
fi

# Code

templates()
{
	local list=
	local temp=
	local update_all=

	for f in ${TPLS}; do
		if [ -n "$PERMS" ]; then
			chmod "$PERMS" "$f"
		fi
		temp="$temp $f"
		if [ -z "$update_all" ]; then
			if [ "${f}.html" -ot "$f" ]; then
				list="$list $f"
			fi
			if [ "$MASTER" -nt "$f.html" ] ; then
				update_all=1
			fi
		fi
	done
	if [ -n "$update_all" ]; then
		list=$temp
	fi
	for f in $list; do
		echo "Updating ${f}.html"
		rm -f "$f.html.tmp" || exit 1
		cat "$MASTER" | while read -r temp; do
			case $temp in
				@menu@)     menu "$f" ;;
				@content@)  cat "$f" ;;
				*)          printf '%s\n' "$temp" ;;
			esac
		done > "$f.html.tmp"
		# Atomically move the new file in place, so
		# no one sees an incomplete file.
		mv -f "$f.html.tmp" "$f.html"
	done
}

if [ -n "$1" ]; then
	unset default
fi

# Targets
for target in "$@" $default; do 
	echo "Building target: $target"
	case "$target" in
		'templates' ) templates ; break ;;
		'gallery'   ) gallery ; break ;;
	esac
done
