#!/bin/sh
#
# $Id: dyndns,v 1.9 2008/05/27 10:27:03 iku Exp $
#
# Copyright (c) 2008 Antti Harri <iku@openbsd.fi>
#

# Common.
PATH=/bin:/sbin:/usr/bin:/usr/sbin
SYSCONFDIR=/home/iku/ohtools/dyndns/etc

#Server
ZONE=/var/named/users/iku/auth/openbsd.fi
HOSTS_DIR=/chroots/home/dyndns
CACHE=/var/tmp/dyndns

# Client
KEY=${SYSCONFDIR}/dyndns.key
CONF=${SYSCONFDIR}/dyndns.conf
USER=dyndns

# No parameters.
if [ -z "$1" ]; then
	exit 1

# Server mode.
elif [ "$1" = "-s" ]; then
	# Init
	cd "$HOSTS_DIR" || exit 1

	# Tmp
	TMP=$(mktemp) || exit 1
	trap "rm -f \"$TMP\"" EXIT

	# Cache dir
	if [ ! -d "$CACHE" ]; then
		mkdir "$CACHE" || exit 1
	fi

	while true; do
		cp "$ZONE" "$TMP" || exit 1
		for h in *.host; do
			cmp -s "$h" "$CACHE/$h"
			if [ "$?" != 0 ]; then
				if [ ! -f "$CACHE/$h" ]; then
					cp "$h" "$CACHE/"
				fi
				MODIFIED=1

				IP=$(cat "$h")
				h=$(echo "$h" | cut -f 1 -d '.')
				perl -pi -e "s/^$h\s+IN\s+A.*/$h\tIN\tA\t$IP/" "$TMP"
				cp "$h" "$CACHE/"
			fi
		done
		if [ "$MODIFIED" = 1 ]; then
			unset MODIFIED
			date=$(date +%Y%m%d%H%M)
			perl -pi -e "s/[[:digit:]]+\s.*serial/$date ; serial/" "$TMP"
			cp "$TMP" "$ZONE" || exit 1
			sudo rndc reload
		fi
		sleep 20
	done

# Client mode.
else
	IP=$(ifconfig "$1" | fgrep 'inet ' | awk '{print $2 }') || exit 1
	MYHOST=$(hostname -s)
	DEST=$(cat $CONF)

	ssh \
		-i "$KEY" \
		-o PasswordAuthentication=no \
		-o BatchMode=yes \
		"${USER}@${DEST}" \
		"echo $IP > ${MYHOST}.host"
fi
