#!/bin/sh
# 
# $Id: chroot_objects,v 1.6 2007/09/09 18:34:37 iku Exp $
#
# Copyright (c) 2007 Antti Harri <iku@openbsd.fi>
#

usage_and_exit()
{
	echo "$0 directory library"
	echo "directory: location of your chroot"
	echo "library: .so file which dependencies to copy"
	exit 1
}

if [ "$#" -lt 2 ] || [ ! -d "$1" ] || [ ! -f "$2" ]; then
	usage_and_exit
fi

get_stuff()
{
# OpenBSD 4.2 and forward can handle files with ldd.
# There's also another matter: readelf didn't list
# all dependencies that xsl.so needed.. weird.
#	type=$(file "$1" | cut -f 2 -d ':')
#	if [ "$(echo $type | fgrep 'shared object')" != "" ]; then
#		tempnames=$(readelf -d "$1" | fgrep " (NEEDED) " | cut -f 2 -d '[' | cut -f 1 -d ']')
#		libnames=
#		for temp in $tempnames; do
#			temp=$(ldconfig -r | fgrep "/${temp}" | awk '{ print $3 }')
#			libnames="$libnames $temp"
#		done
#	elif [ "$(echo $type | fgrep 'executable')" != "" ]; then
		libnames=$(ldd "$1" | egrep -e '(rlib|rtld)' | awk '{ print $7 }')
#	fi
}
parse()
{
	get_stuff "$2"
	for lib in $libnames; do
		libname=$(basename "$lib")
		dir=$(dirname "$lib")

		if [ ! -f "${1}/./${lib}" ]; then
			mkdir -p "${1}/./${dir}/"
			cp -p "$lib" "${1}/./${dir}/"
			echo "${3}${lib}"
			parse "$1" "$lib" "$3  "
		fi
	done
}

echo "starting copy"
parse "$1" "$2" ""
