#!/bin/sh

# FIXME: this script does not support names
# with spaces very well.

PATH=/bin:/sbin:/usr/bin:/usr/sbin
host_start=0
host_end=
host_thres=5
max_wait=2

function usage
{
	echo "nfsdiscover [-l]"
	echo ""
	echo "-l          list mounts in the network"
	exit 1
}

function get_network
{
	# First get the default IPv4 route interface
	local my_iface=$(route -n show | grep '^default' | head -1 | awk '{ print $7 }') 
	# Then get the network
	my_net=$(ifconfig "$my_iface" | grep '[[:space:]]*inet[[:space:]]' | awk '{ print $2 }' | cut -f 1,2,3 -d '.')
	return 0
}
function get_mounts
{
	get_network || return 1

	local cur=$host_start
	local host=
	local failed=0
	local temp=
	local pid=
	found=
	while [ 1 ]; do
		cur=$((cur + 1))
		host="${my_net}.${cur}"
		ping -q -w "$max_wait" -c 1 "$host" 1>/dev/null 2>&1
		# It's alive.
		if [ "$?" -eq 0 ]; then
			temp=$(showmount -e "$host" | grep -e '^/' | awk "{ print \"${host}:\" \$1 }" &)
#			pid=$!
#			local temp2=0
#			while [ 1 ]; do
#				sleep 1
#				temp2=$((temp2 +1 ))
#				if [ "$temp2" -ge "$max_wait" ]; then
#					kill "$pid"
#					break
#				fi
#			done
			found="$found
$temp"
			echo "Found: $temp"
		else
			failed=$((failed + 1))
		fi
		if [ "$failed" -ge "$host_thres" ]; then
			return 1
		fi
	done
}
args=`getopt l $*`
if [ $? -ne 0 ]; then
	usage
	exit
fi

set -- $args
while [ $# -ge 0 ]; do
	case "$1" in
		-l) get_mounts ; shift ;;
		--) shift; break ;; 
	esac
done
