# $OpenBSD$

V =		2.0.1
COMMENT =	tools collection

DISTNAME =	ohtools-${V}
CATEGORIES =	sysutils

HOMEPAGE =	https://github.com/aharri/ohtools

PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

# No distribution site at this time,
# get the git repo and do make distfile.
# MASTER_SITES =

RUN_DEPENDS =	graphics/jhead
NO_BUILD =	Yes
PKG_ARCH =	*
DESTDIRNAME =

.include <bsd.port.mk>
